services:
  ilo-fans-controller:
    build:
      context: https://github.com/alex3025/ilo-fans-controller.git#main
      dockerfile: Dockerfile
    ports:
      - "8084:80"
    environment:
      ILO_HOST: 192.168.1.2
      ILO_USERNAME: Administrator
      ILO_PASSWORD: MyPa$$word
